### ISSUE TITLE
Add license version

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/python-dateutil-feedstock#1]
Appears the [license](https://github.com/dateutil/dateutil/blob/35a4c309823e1d810d57cd37d63a37f114604e76/LICENSE) is BSD 3-Clause. Would be nice to note this in the license field.

**Comment by msarahan** [comment]
done in https://github.com/conda-forge/dateutil-feedstock/commit/8083ebf02f7d4181be269c45bd56b73fe100b4d0
