### ISSUE TITLE
Feedstock name vs package name

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/python-dateutil-feedstock#2]
The package is named `python-dateutil` but the feedstock name, which is derived from the directory name from `staged-recipes`, is `dateutil`. That is not a big deal, but we need to be aware of that to avoid inconsistencies in the future.

**Comment by msarahan** [comment]
argh.  Sorry.  Is there any way to change this?  Remove and resubmit the staged recipe PR?

**Comment by ocefpaf** [comment]
> argh. Sorry. Is there any way to change this? Remove and resubmit the staged recipe PR?

That is the only way I know. Let's just wait for other to weight in to see if that is really needed as `python-dateutil` vs `dateutil` is not too confusing.

**Comment by pelson** [comment]
I think I have fixed this with https://github.com/conda-forge/conda-smithy/commit/eb6bdc9d83db64e86947c04a8876db533d3c3aa6#diff-4970770929969f2ad4e818ed6338e5b1. (conda-smithy v0.10.0).

I will rename the repo on github, and take a look to see if there is other renaming which needs to happen.

**Comment by pelson** [comment]
That was quite an arduous task - I needed to change the repo name, remove the AppVeyor project and synch travis. CircleCI just worked though.

We are going to want to automate as much of that as possible in the future (i.e. all of it!). 😄
