### ISSUE TITLE
@conda-forge-admin, please update version

### ISSUE THREAD

**Issue by Petzep** [conda-forge/python-dateutil-feedstock#27]
### Additional comment:

A [hotfix](https://github.com/dateutil/dateutil/releases/tag/2.9.0.post0) of `python-dateutil` was released shortly after `2.9.0` was released.

Can this feedstock be updated to version `2.9.0.post0`?

**Comment by ocefpaf** [comment]
Looks like we don't need the post release. Please reopen if this assessment is wrong.

**Comment by thewchan** [comment]
@ocefpaf this recipe is specifically calling to depend on 2.9.0.post0 https://github.com/conda-forge/dataconf-feedstock/pull/24. Would it be okay to provide that?

**Comment by thewchan** [comment]
CC: @Petzep
