### ISSUE TITLE
Support 2.9.0.post0

### ISSUE THREAD

**Issue by thewchan** [conda-forge/python-dateutil-feedstock#29]
### Comment:

@msarahan @ocefpaf @pganssle Quick request to support `2.9.0.post0` I have a downstream project that needs it here: https://github.com/conda-forge/dataconf-feedstock/pull/24

Thanks!

**Comment by ocefpaf** [comment]
See https://github.com/conda-forge/python-dateutil-feedstock/pull/26

Post releases are not new releases, they just fix the wheel. This downstream package should not pin to it :-/

**Comment by thewchan** [comment]
Okay I guess I can just get rid of pip check for now downstream?

**Comment by ocefpaf** [comment]
> Okay I guess I can just get rid of pip check for now downstream?

Add a comment so you can restore it when a new release is out.

**Comment by xylar** [comment]
I'm running into pip-check problems, too.  I think it would be easier if we waste a little time making `post0` releases so we don't have to waste time disabling and re-enabling `pip check`...

**Comment by ocefpaf** [comment]
> I'm running into pip-check problems, too. I think it would be easier if we waste a little time making `post0` releases so we don't have to waste time disabling and re-enabling `pip check`...

We are accumulating workaround b/c people are abusing pins :-(

OK. Let's do that then.

**Comment by thewchan** [comment]
Should I PR to bring up `post0` or is someone from the maintainer team planning to handle this?
